version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_MODE=raft  # Modo Raft
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL=PLAINTEXT  # Protocolo de segurança
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT  # Mapeamento de protocolo
      - KAFKA_LISTENER_NAME_DEFAULT=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - ALLOW_PLAINTEXT_LISTENER=yes  # Permite conexões sem segurança
    ports:
      - "9092:9092"
